### PR TITLE
More Workshop updates

### PR DESCRIPTION
**Pull request by peacegiverman**
I added support for the item installed callback which fires when a subscribed item is downloaded. I also added support for methods which check item upload/download progress (`GetItemUpdateProgress` and `GetItemDownloadInfo`).

Along the way I also updated the `ActivateGameOverlay` function and added `ActivateGameOverlayToWebPage`.

### CODE REVIEW

**Comment by Gramps** [comment]
Nice!  I'll check it out and merge it in.  Had to change the install process a bit as some part of the code uses C++11 specific naming and the original install steps stopped working.

You guys compiling in Linux or Windows or both?

**Comment by peacegiverman** [comment]
On Windows so far, but I'll have to start testing it on Linux now.

**Comment by Gramps** [comment]
Nice.  Does your process vary from the one listed?  I haven't tried compiling it in Windows yet, but have done so in Linux.

**Comment by peacegiverman** [comment]
Yeah, it's just like in the readme, built with VS2015. I'm going to try it with VS2010 now.

**Comment by Gramps** [comment]
Great, glad no changes need made!

**Pull request merged**
