### PR TITLE
Reworked steamworks.py into Python module

### PR DESCRIPTION
**Pull request by philippj**
I found it initially quite hard to start working with the current implementation, so I want to suggest building an actual module.

Alongside this PR is the initial commit - which is by no means finished - of all current interface implementations except `SteamController` as that was deprecated some time ago.

As this is a rather big change I would appreciate your input @Gramps on this topic and to know if you approve of this.

### CODE REVIEW

**Comment by Gramps** [comment]
Wow, that is a thing of beauty, sir.  I have been meaning to completely overhaul the whole thing for a while as it has become cumbersome to work with, as you noticed.

Didn't know SteamController was depreciated.  Time to start gutting that out then.

I almost wonder if this should be pushed to the experimental branch to prevent issues with folks already using it or perhaps move the current master to a legacy branch.

Again, fantastic work!  I will get the master branch moved to a new legacy branch then merge this in and make it our new base.

**Comment by Gramps** [comment]
We are go!

**Comment by skyfpv** [comment]
Any chance we could get someone to update the documentation on the website to mention the steamworks folder instead of steamworks.py? I'm setting this up for the first time and got pretty confused until I found this merge request. Also, thanks for all the hard work!

**Comment by Gramps** [comment]
Yep, it is in the works.  Updates on my end have been really slow since I moved over to Godot Engine a few years a back; this project has also fallen pretty low on my priorities.  That being said, I have a very large update in the works and documentation is a part of it.

**Pull request merged**
