### PR TITLE
Updated example to be compatible with Python 3.8

### PR DESCRIPTION
**Pull request by philippj**
Added change suggested in #43

### CODE REVIEW

**Comment by Gramps** [comment]
Looks good, sir!  Also, would you be interested in taking over the project?  I could stay on for documenting and adding code when possible, but I don't know I have much time left over for it.

**Comment by philippj** [comment]
@Gramps Sure. Would be a shame to see this project getting abandoned

**Comment by Gramps** [comment]
@philippj Would it make more sense to transfer the repo to you or add you as a collaborator in the settings?  I'm not sure what all transferring it does.  If if changed the main URL, I"ll contact Valve to have them change it in the Steamworks documentation.

**Comment by philippj** [comment]
@Gramps I think transferring would be better in the long run. Not sure how redirects are handled post rename & transfer so you should contact Valve about that.

Should you need my e-mail for anything: `philipp@philippj.com`

**Comment by Gramps** [comment]
@philippj Sounds good.  I'll do the transfer this evening and make note of everything that changes.  I'll contact them on Monday.

**Comment by Gramps** [comment]
Hmm, it won't let me transfer it to you because you already have a SteamworksPy repo.  I guess you can delete it then I can transfer it over.  If you want, afterwards you can add me as a collaborator if you wish and I can continue to do updates when I have time.

**Comment by philippj** [comment]
@Gramps Well, I forgot to delete my fork. I just deleted it, so you should now be able to transfer it.

**Comment by Gramps** [comment]
Alright, transfer request sent.

**Pull request merged**
