### PR TITLE
Automated building of win-64 dll via Travis and bugfixes for workshop

### PR DESCRIPTION
**Pull request by philippj**
I added a first Travis config for Windows (64 bit). Utilizing TravisCI for automated builds will require manual setup for the main repository.

### CODE REVIEW

**Comment by Gramps** [comment]
Sadly I cannot approve this pull request because it contains actually Steamworks files.  We can't push Valve's actually Steamworks files as far as I know.   I would put a git ignore in that folder and resubmit.

**Comment by philippj** [comment]
Hey @Gramps, 

I am by no means a legal expert but by my understanding of the license agreement Valve allows the use of the SDK to use and reproduce the SDK in source code form. Additionally Facepunch also has the SDK source code included in their public repository ( https://github.com/Facepunch/Facepunch.Steamworks/tree/master/Generator/steam_sdk ). 

However If you feel uncomfortable with the source being in the repository I will try to contact Valve and get their stance on this. 

Automatic builds would be a pleasant feature to have and honestly it would be in their interest to push SDK adoption to more platforms.

**Comment by Gramps** [comment]
I was always under the assumption we weren't allowed to add it, but I could be wrong.  I figured it would be more accessible on their site without making any agreements otherwise.

If it is fine to have it up, then that's good.  I guess I can reach out to them to get an official response.

**Comment by Gramps** [comment]
Hey there, figured I had responded to this already.  Sorry for the delay!

So I got a response and it seems that technically we are only supposed to distribute the redistributables.  The rest of the SDK isn't supposed to be uploaded though older headers are indeed available on Github.  I haven't fully gone through the ToS and developer agreement though.

That being said, we will probably want to alter the pull request to remove the SDK.   As for Facepunch, not sure why they have it all on there but they do.

**Comment by philippj** [comment]
As the raw SDK files are required for building and the download is behind a login I can scrap the building process. I will replace the automatic building with a couple of scripts.

**Comment by Gramps** [comment]
Sounds good.  If I get any further information about pointing to it is allowed to be added, we can put it back in.

**Comment by philippj** [comment]
I removed the SDK and adjusted the environment for manual builds. For now I only added Windows 64bit as I can only test that on my personal rig. 

Something I want to suggest is to have intermediate builds ready in the main repository so that development versions can still be tested and used by others without the need to build it themselves.

**Comment by Gramps** [comment]
Looks good, sir!  I can get a Linux test done this weekend.

I do agree with your suggestion of having intermediate builds available.  Definitely nice to have so people can get to using it immediately.

**Pull request merged**
